[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-static",
  "-C", "link-arg=-no-pie",
  "-C", "relocation-model=static",
  "-C", "link-arg=-Wl,--nmagic",
]

[target.aarch64-unknown-linux-gnu]
rustflags = [
  "-C", "link-arg=-nostartfiles",
  "-C", "link-arg=-static",
  "-C", "link-arg=-no-pie",
  "-C", "relocation-model=static",
  "-C", "link-arg=-Wl,--nmagic",
]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-lSystem"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-lSystem"]

[target.x86_64-pc-windows-msvc]
rustflags = []

[target.x86_64-pc-windows-gnu]
rustflags = []
